name: release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.21.1
      - name: Update npm
        run: |
          npm install -g npm
          npm --version
      - uses: actions/checkout@v5.0.0
      - name: Install dependencies
        uses: bahmutov/npm-install@v1.11.1
        with:
          useLockFile: false
      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
